### PR TITLE
Restructure packages

### PR DESCRIPTION
**Pull request by bensimner**
Needs double-checking but should be okay

### CODE REVIEW

**Comment by HarveyHunt** [comment]
We should also update Travis to run the tests, but we can do that later :+1:

**Comment by bensimner** [comment]
Yeah, travis' failure here is because the actual tests I have are meaningless and don't follow flake8... but that's okay because we can delete them, they were just an example of how to run tests :)

**Comment by Chippiewill** [comment]
Could you either remove the tests or fix them for flake8, otherwise we'll have a hard time enforcing style checks

**Comment by HarveyHunt** [comment]
I'll remove them this afternoon when I send a PR containing real tests

**Pull request merged**
